- sourmash
- sourmash_lib.py
also remove python2 on hashbang.
> unicode() not available on py3

- .travis.yml
- sourmash
- test.sh
- tox.ini
Uses tox for running tests on 2.7 and 3.5 (and add a basic travis config)
``` bash
$ pip install tox
$ tox
```
> Test runner

- sourmash_lib/_minhash.cc
- sourmash_lib/_minhash.hh
- sourmash_lib/kmer_min_hash.hh
- sourmash_lib/test__minhash.py
Initial changes to expose hashing seed used at C-level as a parameter (see issue #76).
If deemed reasonable this can be propagated up to command-line.
> Seed when computing hashes now a parameter for all C-level

- sourmash_lib/__init__.py
- sourmash_lib/__main__.py
- sourmash_lib/_minhash.cc
- sourmash_lib/signature.py
- sourmash_lib/signature_json.py
- sourmash_lib/test_estimators.py
- sourmash_lib/test_signature.py
Update to #83.
* Adds `--scaled` to `sourmash compute`
* Adds `max_hash` to `Estimator` and `SourmashSignature`;
* Fixes bug with `abundances` saving/loading in `Estimators`;
* Fixes issue with Jaccard similarity computation for empty `MinHash` objects;
> Boundary try

- sourmash_lib/_minhash.cc
- sourmash_lib/kmer_min_hash.hh
- sourmash_lib/test__minhash.py
Fixes #73 Raise an exception when calling `set_abundances` on a KmerMinHash instance instead of a KmerMinAbundance instance.
> Fix segfault in MinHash.set_abundances

- sourmash_lib/__main__.py
This is solely deindentation and minor refactoring of `__main__` - no functionality change, but
the new structure permits more flexibility by moving the subcommands out of the class.
> refactor __main__ so that commands are not in a class

- sourmash_lib/_minhash.pxd
- sourmash_lib/kmer_min_hash.hh
- sourmash_lib/test__minhash.py
Keep the list of N minimum hash values dense and cache local by using a vector instead of a set.
Thoughts on the general sentiment?
I used `time_add_sequence` and `time_add_hash` from #100 as benchmarks:
| bench | add_sequence | add_hash |
|----------|-----------|------------|
| master | 0.81 | 0.16 |
| d92a3da | 0.68 | 0.11 |
| 0e6ec9e | 0.60 | 0.11 |
| 55bc2ad | 0.56 | 0.11 |
There are a few tests that don't yet pass and we can be much smarter in the `combine` methods. Before spending time cleaning it up: is the performance boost worth it? is the benchmark I used useful or should I try something else to conclude that it does speed things up?
> [MRG] Speed up MinHash by using a vector instead of a set

- sourmash_lib/__main__.py
- sourmash_lib/test_sourmash.py
Should address issue #109.
The high-level reading function is guessing the file format so I kept that logic in the converter. The converter is advertised to ensure conversion (meaning that JSON files can be given as input and one should not worry about sorting out which file is what beforehand) and
all resulting signature files have a `.json` extension added.
> subcommand to convert from YAML to JSON

- sourmash_lib/commands.py
- sourmash_lib/sbtmh.py
- sourmash_lib/test_sourmash.py
note, PR into #135.
also fixes a bug in find_best when threshold is set to 0.
-----
> refactor the sbt_gather code to be sane(r)

- sourmash_lib/test_sourmash.py
Fixes the time stamp issue mentioned https://github.com/dib-lab/sourmash/issues/139#issuecomment-283011301
sleep() between creating two time stamps to ensure they are different.
> Fix timestamp compare by sleeping

- sourmash_lib/sbt.py
- sourmash_lib/sbtmh.py
Use lazy loading of the `.data` property in `Node`, `Leaf` and `SigLeaf`.
(This also opens the path for using a cache for the data in the nodes: load all the nodes to memory, but only load the data when needed and with an upper bound for how much data can be loaded).
> [MRG] Refactor lazy loading

- sourmash_lib/__main__.py
- sourmash_lib/commands.py
- sourmash_lib/sbt.py
- tests/conftest.py
- tests/sourmash_tst_utils.py
- tests/test_sbt.py
- tests/test_sourmash.py
Fixes #141 
The initial implementation just went thru the leaves in another tree and add to the original one. This is not so efficient because we recreate internal nodes (a lot).
A better solution is to create a new root, make each original tree a child of the new root, and reuse all the internal nodes already calculated. This is implemented now.
Possible improvements:
1) The current solution (create a new root) works well with binary trees, but if d>2 we could instead check to see if there is a position available near the root before inserting. This is more visible if you try to combine trees in sequence.
2) Since I'm not reorganizing the tree properly, the next available position will be between the combine trees (there might be an empty position on the left tree before we inserted on …
> [MRG] SBT feature: combine trees

- sourmash_lib/commands.py
- tests/test_sourmash.py
Fixes #167.
@taylorreiter @brooksph could one of you try this out and provide a small snippet of R code for reading in the resulting matrix? thx!
> [WIP] Add --csv output to 'sourmash compare'

- sourmash_lib/_minhash.pyx
- sourmash_lib/commands.py
- sourmash_lib/sbtmh.py
- sourmash_lib/signature.py
- tests/test_signature.py
- tests/test_sourmash.py
Fixes #146 (a bug in sbt_search). Also fixes #182 (`--containment` option in search).
> [MRG] Apply downsampling magic to sbt_search

- sourmash_lib/commands.py
- sourmash_lib/sbt.py
- tests/test_sourmash.py
> [MRG] Add append option to sbt_index

- .travis.yml
- setup.py
- tox.ini
- set 3.6 as the default in travis
- run tests for 2.7, 3.5 and 3.6
- remove classifiers for 3.3 and 3.4, add for 3.6
> [MRG] Travis and tox updates

- doc/tutorials.md
- requirements.txt
- sourmash_lib/sbt.py
- tox.ini
Updated docs to install khmer from PyPI, same with tox and requirements.txt
Also remove need to have `numpy` for commands that don't need `numpy`.
> [MRG] Use khmer from PyPI now that 2.1 is released

- sourmash_lib/_minhash.pyx
- tests/test__minhash.py
I was talking with @halexand yesterday and the intersection seems to be a common use case. `compare` already does what is needed but return the similarity, so I moved most of the code to `intersection` and then implemented `compare` using `intersection`.
> [MRG] Split MinHash.compare in two: intersection and compare

- sourmash_lib/_minhash.pxd
- sourmash_lib/_minhash.pyx
- sourmash_lib/kmer_min_hash.hh
> [MRG] Let's fix this C++/Cython mess

- .travis.yml
Our travis config assumed different Python versions were installed, which doesn't seem to be true anymore (see https://travis-ci.org/dib-lab/sourmash/jobs/274623549). This PR fixes it by being explicit about which Python version to use.
> [MRG] Use a build matrix and be explicit about python version

- sourmash_lib/_minhash.pyx
- sourmash_lib/commands.py
- sourmash_lib/kmer_min_hash.hh
- sourmash_lib/sbtmh.py
- sourmash_lib/signature.py
- sourmash_lib/signature_json.py
- tests/test__minhash.py
- tests/test_sourmash.py
This PR makes `len(minhash)` equal to `len(minhash.get_mins()`, and also makes sure that `num=0` when max_hash is set and `max_hash=0` when it is not set - fixes #214.  Associated changes and refactoring occurred as well, including the removal of a test for unwanted behavior around num=0, and some code for legacy loading of signatures where n was saved as -1 (== 4294967295).
> [MRG] make len(minhash), minhash.num, and minhash.max_hash => sensible.

- sourmash_lib/signature.py
- tests/test_signature.py
In `load_signatures` and `load_one_signature`, convert `select_ksize` to an int value explicitly.
(This is a silly little problem that tripped me up in another project; thought it was worth fixing.)
> [MRG] Fix a problem with non-int select_ksize parameters to load_signature

- sourmash_lib/commands.py
- sourmash_lib/logging.py
- sourmash_lib/sourmash_args.py
- tests/test_sourmash.py
Updates to `sourmash compare` --
* downsample to lowest `scaled` value if `max_hash` is set. (fixes #285)
* error out with informative messages if multiple k-mer sizes or molecule types are present.
* add `--dna` and `--protein` arguments (fixes #168);
* fixes `sourmash compute` output annoyance (fixes #286);
> [MRG] upgrade `sourmash compare` to do downsampling, ksize checks, and more.

- doc/tutorials.md
- sourmash_lib/__init__.py
- sourmash_lib/_minhash.pyx
- sourmash_lib/commands.py
- sourmash_lib/sbtmh.py
- sourmash_lib/signature.py
- tests/test__minhash.py
- tests/test_api.py
- tests/test_sourmash.py
A few useful changes to the Python API, partially addressing #308.
* `load_signatures`, `load_one_signature`, `SourmashSignature`, and `save_signatures` are now available at the top-level in the package (addresses #305);
* added two new convenience functions, `get_max_hash_for_scaled` and `get_scaled_for_max_hash`, to `_minhash` module;
* `MinHash` constructor now takes EITHER `max_hash` OR `scaled` values (fixes #321);
* fixes some minor tutorial issues (fixes #290, #287);
* basic checks on `sourmash compute --scaled` value (fixes #291);
* provided nicer API for search (fixes #308);
* added `--randomize` to `sourmash compute` (fixes #322);
> [MRG] Updates and improvements and simplifications to the sourmash Python API

- sourmash_lib/_minhash.pyx
- sourmash_lib/kmer_min_hash.hh
- tests/test__minhash.py
- tests/test_signature.py
This fixes #319, as well as an associated bug when inserting new hashes into the middle of the sketch. #319 was a segfault caused by invalidation of iterators when increasing the capacity of a vector.
Two new tests were added targeting both bugs; see the bottom of `test__minhash.py`.
As part of this PR, I altered the behavior to no longer allow bounded sketches with `max_hash` or `scaled`, and adjusted tests to match. Only one explicit test existed for this behavior and the note on the test said `not sure sensible use case...` so I don't feel guilty about this.
> [MRG] Fix segfault when using --track-abundance

- sourmash_lib/_minhash.pyx
- tests/test__minhash.py
This is a partial bug fix for a segfault when computing `similarity` between two `MinHash` objects, one created with `track_abundance=True` and one without.  The underlying cause of the crash is in the `merge` function, discussed in #346, but this crash is reachable from the command line and moreover is getting in the way of another PR so I am fixing it first!
> [MRG] fix a segfault in the 'MinHash.similarity' code when mixing --track-abundance and flat signatures

- sourmash_lib/signature.py
- tests/test_signature.py
Add `__str__`, `__repr__`, and `__hash__` to `SourmashSignature` objects.
> [MRG] make SourmashSignature printable and hashable

- sourmash_lib/_minhash.pyx
- sourmash_lib/kmer_min_hash.hh
- tests/test__minhash.py
Fixes #346 
`__iadd__` (the implementation for `merge`) was casting improperly to `KmerMinAbundance` when not tracking abundance in one of the operands, causing C++ to pick the wrong method. Just needed to check if both operands track abundance, and everything works properly.
(Fixing this was easier than expected.)
> [MRG] Cast to the proper type on merge with track_abundance

- doc/command-line.rst
- sourmash_lib/commands.py
- tests/test_sourmash.py
This adds `--subsample <N>` and `--subsample-seed <R>` to `sourmash plot`, which will plot a randomly chosen subset of size N, chosen using Python's `random.shuffle`, seeded with `--subsample-seed`.  Note that the seed defaults to 1, which intentionally gives stable results when used with the same inputs.
Fixes #221.
Also fixes #334, detecting multiple ksizes/moltypes earlier.
> [MRG] plot a random subsample with 'sourmash plot --subsample'.

- sourmash_lib/kmer_min_hash.hh
- tests/test__minhash.py
The exception raised by `MinHash.add_sequence` on bad DNA contains the wrong character.
> [MRG] fix reporting of bad DNA ch

- sourmash_lib/commands.py
- sourmash_lib/signature.py
- sourmash_lib/signature_json.py
- sourmash_lib/sourmash_args.py
- tests/test_signature.py
Changed all arguments of 'select_ksize' to 'ksize' in sourmash/lib. Fixes issue #305 
> select_ksize to ksize fix/issue #305

- sourmash_lib/commands.py
- tests/test__minhash.py
- tests/test_sourmash.py
Fixes #358
Since the distance is symmetrical (`E1.compare(E2) == E2.compare(E1)`)
we only need to calculate the top half of the matrix and mirror it.
> Faster compare by exploiting symmetry

- sourmash_lib/_minhash.pyx
- tests/test__minhash.py
> [MRG] fix rounding error in get_scaled_for_max_hash

- doc/api-example.rst
- sourmash_lib/commands.py
- sourmash_lib/signature.py
- sourmash_lib/signature_json.py
- tests/test_api.py
- tests/test_signature.py
- tests/test_signature_json.py
- tests/test_sourmash.py
This is a wholesale removal of the 'email' and 'type' fields in signatures, both in the Python class and the JSON signature format.
Fixes #292 #58. Also see #268.
> [MRG] remove 'email' and 'type' from signatures.

- doc/index.rst
- sourmash_lib/search.py
- sourmash_lib/sourmash_args.py
Fixes #379 (the `notify` part)
Also:
- Add link to LCA tutorial to docs index
- Fix loaded signatures reporting
#
> [MRG] Add missing import

- sourmash_lib/sbt.py
- tests/test_sbt.py
These were preventing #380 from being merged. The issue was that `max_n_below` wasn't being propagated on `repair`, and also the `combine` test was a bit too dumb and broke when I stopped depending on some defaultdict behavior.
> [MRG] Fix repair and combine errors

- README.md
I added additional information about the conda install. It is important to setup channels correctly in advance to be able to use the conda install command. An alternative is to add channels together with the install command using `-c`.
> Extend conda section

- doc/api-example.md
- pytest.ini
had to fix pytest configuration to use `.md` files as the right extension for doctests, and also add empty lines in the right places.
> [MRG] fix doctest in markdown files

- sourmash/commands.py
- sourmash/sourmash_args.py
This lets us do
```
sourmash index genbank-k31 ../.sbt.genbank-k31 --traverse-directory -f
```
to reindex SBTs, etc. etc.
> [MRG] Add --force flag to 'sourmash index'

- sourmash/kmer_min_hash.hh
- tests/test__minhash.py
...I cannot believe it took until now to find this bug.
> [MRG] fix a problem where sourmash ignores all lowercase sequence.

- sourmash/sbt.py
- sourmash/sbtmh.py
- tests/test_sourmash.py
`min_n_below` was always `1` (since we were doing `min(some_number, 1)`. Fix it by doing `min(some_number, sys.maxsize)` instead.
Also fix a formatting detail in the `test_do_traverse_directory_compare` test, if files are read in a different order it won't fail the test.
> Fix min_n_below calculation

- sourmash/kmer_min_hash.hh
- tests/test__minhash.py
Per https://github.com/dib-lab/sourmash/issues/502#issuecomment-399084320, this fixes a problem where the wrong "bad" character was being reported out from --check-sequence.
The root of the problem was an bad attempt to figure out exactly which character was causing problems. This is a conservative fix that simply reports the whole k-mer that is causing problems, which should be sufficient.
Fixes #502.
> [MRG] Fix reporting of bad characters in input by reporting entire k-mer

- README.md
- doc/databases.md
- setup.py
It's been some time since we uploaded releases to PyPI, and things changed:
- Warehouse was deployed, so it supports Markdown in the `long_description` field. I decided to put the `README.md` file there (which makes GitHub and PyPI look the same)
- Markdown support requires `setuptools>=38.6.0`, which is a fairly recent version. I bumped the version in `setup.py`, so this would probably also fix https://github.com/dib-lab/sourmash/issues/173
- Update README to point to pre-releases instead of installing from master
- Update DBs in docs (for 2.0.0a8)
> [MRG] PyPI fixes

- setup.py
- sourmash/sbt.py
Fixes `load_nodegraph` being removed from `khmer 3`.
(Travis is testing only on khmer 2.1.1, should we put a matrix config to check on both khmer 2 and 3? My vote is no.)
> [MRG] make sourmash compatible with khmer 3

- sourmash/sbtmh.py
While doing profiling on `sourmash gather` I found out this line is where we spend almost all the runtime:
`matches = sum(1 for value in hashes if node.data.get(value))`
This makes sense, since it's the part where we check if the hashes are in the internal node Bloom Filter.
Turns out doing `node.data` takes some time, so replacing the line with
```
get = node.data.get
matches = sum(1 for value in hashes if get(value))
```
gives us ~40% reduced runtime. Yay!
Ready for review and merge @ctb
> [MRG] Avoid calling node.data

- sourmash/commands.py
fixes #535 by moving the print outside the loop, so the upper right side of the matrix gets calculated
before printout.
> [MRG] fix print_results output of compare to print out symmetric matrix

- sourmash/commands.py
> Explicitly state default thresholds in help text

- sourmash/commands.py
- sourmash/search.py
- tests/test_sourmash.py
Addresses https://github.com/dib-lab/sourmash/issues/541
> Add --ignore-abundance to "search" and "categorize"

- requirements.txt
- setup.py
- sourmash/commands.py
- sourmash/tenx.py
- tox.ini
> Make 10x support optional

- .coveragerc
- .travis.yml
- Makefile
- doc/api-example.md
- sourmash/lca/command_index.py
- sourmash/sbt.py
- sourmash/sbtmh.py
- sourmash/signature.py
- sourmash/signature_json.py
- tests/test_deprecated.py
This fixes #544 and add some testing improvements:
- testing with python 3.7
- clean up coverage reports
- `make test` now uses `-e` for pip (avoids reinstallation issues)
- `ijson` has different backends, and we always used the slower one (even with the faster ones available)
- the default one (pure Python) was throwing `DeprecationWarning` (because a generator was raising `StopIteration`, which is a [warning on 3.6 and an error in 3.7](https://www.python.org/dev/peps/pep-0479/#transition-plan)
- any of the optimized ones was throwing errors because we were passing 'text mode' files, when they were expecting 'byte mode' files
- I found a way to fix this without changing the API, but still figuring out how to avoid changing an API doctest.
without a major version increment. Changing file …
> [MRG] Fix JSON loading

- doc/tutorials.md
updates documentation to include definitions for `sourmash gather`'s csv output
> [MRG] Update/doc tr

- README.md
- paper.bib
Same as https://github.com/dib-lab/khmer/pull/1881 ;-)
- ~~`make test` Did it pass the tests?~~
- ~~`make coverage` Is the new code covered?~~
- ~~Did it change the command-line interface? Only additions are allowed
major version number increment.~~
- ~~Was a spellchecker run on the source code and documentation after
changes were made?~~
> Hyperlink DOIs to preferred resolver

- sourmash/_minhash.pyx
- tests/test__minhash.py
> [MERGE] fix divide by zero issue in MinHash.contained_by

- README.md
Update README to prefer bioconda install; see #552. This can be merged now, before the 2.0 release.
See #592 for changes to made for the sourmash 2.0 release. I think the tutorial fix should probably be done post-release.
> [MRG] update readme for bioconda install

- sourmash/_minhash.pyx
- tests/test__minhash.py
thx @halexand for finding the bug :)
> [MRG] Make sure either scaled or num is set on `MinHash(...)` construction

- sourmash/_minhash.pxd
- sourmash/_minhash.pyx
- sourmash/kmer_min_hash.hh
- sourmash/sbtmh.py
- sourmash/search.py
- tests/test__minhash.py
A couple of fixes for gather perf problems
- don't recalculate scaled query minhash everytime we reach a leaf in the SBT
- add a `remove_many` method to remove hashes from a minhash
- use the `remove_many` method to remove matches from the query (instead of building a new one). This makes a huge difference for large queries.
I ran `master` with a large metagenome query, got 4 matches in 17h. This PR takes 17 minutes to find the same matches.
> [MRG] gather optimizations

- CITATION.cff
- doc/index.rst
- sourmash/__main__.py
- sourmash/commands.py
- sourmash/lca/command_classify.py
- sourmash/lca/command_compare_csv.py
- sourmash/lca/command_gather.py
- sourmash/lca/command_index.py
- sourmash/lca/command_rankinfo.py
- sourmash/lca/command_summarize.py
- sourmash/sig/__main__.py
- sourmash/sourmash_args.py
Per #259. #478 is probably a better solution, but this is complementary?
> [MRG] add citation output

- .travis.yml
- sourmash/sbt_storage.py
- tests/test_sbt.py
- tox.ini
The Python IPFS client recently changed its name and a bit of the API.
> Update ipfsapi dependency

- sourmash/_minhash.pyx
The intersection function uses the `new` operator to construct
a `KmerMinHash` or `KmerMinAbundance`. Although this is Cython,
`new` still heap-allocates the object, and it is *not* marked
for garbage collection, because it isn't a PyObject. This commit
calls delete (`del`) on the allocated object to prevent it from
being leaked.
Addresses #685.
> Fix memory leak in `MinHash.intersection`.

- tests/test__minhash.py
- tests/test_lca.py
Master branch is broken because pytest 5 changed how to check for exception messages. This PR fixes the checks.
> Fix exception assertions

- Cargo.toml
- src/lib.rs
- src/sketch/minhash.rs
- src/wasm.rs
Main changes:
- Using forks from [pdatastructs.rs](https://github.com/luizirber/pdatastructs.rs/tree/succinct_wasm) and [succinct-rs](https://github.com/luizirber/succinct-rs/tree/wasm_fix) to fix wasm compilation (which is used in parts that are not really exposed in wasm...)
- change the UKHS code to use rust-boomhpf instead of bbhash, because bbhash-sys is C++ and therefore not compilable with the `wasm32-unknown-unknown` toolchain. Main issue here is that `rust-boomphf` is not compatible with `bbhash` (different hashes being used), so it breaks compatibility... Thinking about fixing it (eventually).
> Fix wasm compilation

- sourmash/commands.py
> [MRG] Update docstring for `--traverse-directory` on `sourmash index`

- sourmash/commands.py
- tests/test_sourmash.py
> [MRG] Fix --output-unassigned to output abundances if available.

- setup.py
- sourmash/sbt.py
- tests/test_sbt.py
- tests/test_sourmash.py
This brings the minimum v5 support from #456 (internal changes and loading from file), while still defaulting to saving to v4. This allows experimenting with the format without commiting to full support (yet).
Differences from v4 to v5:
- Internal representation uses two dictionaries: one for internal nodes, another for leaves.
- Only leaves are required to be present in the SBT file, and it will rebuild internal nodes on load.
- Prototype for insertion without updating internal nodes (delay internal node generation to save)
(v5 is the default in the rust codebase)
> Experimental v5 SBT format

- sourmash/_minhash.pxd
- sourmash/kmer_min_hash.hh
Removes a bunch of unnecessary string copying and adds some "unsafe" methods for hashing and sanity checking which accept C-strings (`const char *`) instead of `std::string`.
Note that this makes `KmerMinHash::add_sequence` volatile: the `sequence` is no longer passed as `const`. However, the user-facing interface always makes a copy of the incoming Python `str` in the Cython layer, so this volatility is discarded.
> Optimize KmerMinHash add_sequence

- sourmash/_minhash.pxd
- sourmash/_minhash.pyx
- tests/test__minhash.py
I was working on a script and triggered a segfault by setting `.track_abundance = True` and then calling `.set_abundances`. For now a test reproducing the bug, working on fixing it.
> Bug: segfault with set_abundances

- .github/workflows/asv.yml
- MANIFEST.in
- asv.conf.json
- benchmarks/benchmarks.py
At some point we configured `asv` to run benchmarks, but it was never integrated into CI (or had many benchmarks implemented). Working on improving the situation =]
This is a start, making `asv` run without dependencies on `tests/`. It would be better to have a fixed set of data in every run (even thought is unlikely that the random data will be extremely biased for one specific comparison in the benchmarks), but maybe do that in #128.
I also added the first github action to the repo. This way we don't extend our running time on Travis. The benchmark check is not required (for now), but it is nice to have some performance tracking that doesn't required running `asv` locally or depending on PR submitter self-reporting.
without a major version increment. Changing file formats also requires …
> Fix asv benchmarks

- sourmash/sig/__main__.py
- tests/test_cmd_signature.py
This PR adds an option `--abundances-from/-A` to `sourmash signature intersect` that allows the user to specify a specific signature from which to preserve abundances in the output signature.
Ref #743.
> [MRG] add optional abundance preservation to sourmash signature intersect

- sourmash/signature_json.py
- tests/test_signature.py
(Yes, it's one of those days)
This will fail in Python 3:
```python
with open(output, "wb") as fp:
sourmash.save_signatures([query], fp)
```
because there is a call to `unicode(s)` and `unicode()` doesn't exist in Python 3 anymore:
```python-traceback
Traceback (most recent call last):
File "src/sourmash/sourmash/signature_json.py", line 279, in write_records_to_json
fp.write(s)
TypeError: a bytes-like object is required, not 'str'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "unassigned.py", line 54, in <module>
sourmash.save_signatures([query], fp)
File "/home/chick/Envs/2019-10-17-unassigned_hashes-gY7Uf7Ke/src/sourmash/sourmash/signature.py", line 262, in save_signatures
return signature_json.save_signatures_json(siglist, …
```
> Bug: save_signatures with a file opened in binary mode fails

- .github/workflows/asv.yml
- Makefile
Oops, it was not comparing the current PR against master, but the two previous commits in master to each other...
> Fix asv benchmark action

- .travis.yml
- Cargo.toml
- src/index/sbt/mod.rs
- src/lib.rs
- src/sketch/minhash.rs
`wasm32-unknown-unknown` (the webassembly target for browsers) and `wasm32-wasi` both have the same target arch, so change the conditional compilation to account for that.
(also avoid a call to `.canonicalize()` because that's not implemented in WASI std yet...)
> Fixes for WASI compilation

- sourmash/commands.py
- sourmash/index.py
- sourmash/lca/lca_utils.py
- sourmash/sbt.py
- tests/test_index.py
- tests/test_lca.py
- tests/test_sbt.py
NOTE: this is a PR into #556.
Some quick notes for @luizirber -
* the SBT class has `insert` already defined but it takes different arguments than `Index.insert`.
* at least at the moment LCA indices don't support inserting.
> [WIP] add signatures() method to both LCA and SBT indices

- doc/developer.md
- setup.py
> update dev docs and add recommonmark as a test dependency

- include/sourmash.h
- sourmash/_minhash.py
- src/ffi/minhash.rs
Oops. It was particularly bad with `gather`...
> fix mem leak in get_mins

- .github/workflows/rust.yml
- Cargo.toml
- include/sourmash.h
- sourmash/_minhash.py
- sourmash/commands.py
- src/errors.rs
- src/ffi/minhash.rs
- src/sketch/minhash.rs
- tests/minhash.rs
- tests/test__minhash.py
Similarity calculations had to call `.merge()` (to check if minhashes are compatible), `.get_mins()` (which copies a lot of data) and calculate the `dotproduct` in Python, so moving this into Rust makes things... faster. I used [sourmash_benchmarks][0] to run a compare test, and for that benchmark (using 380 signatures from the genbank k51 SBT) it takes 30s now (down from 90s in `2.3.1`).
[0]: https://github.com/luizirber/sourmash_resources/blob/4ad31d87866049e1d291b7651af85c2e473309ec/README.md#compare
I also changed `compare` to avoid downsampling a signature if it is already at the right scaled.
(Incidentally, also avoids calling `.merge()` and leaking memory :see_no_evil:)
changes …
> [MRG] Move similarity with abundance into Rust

- sourmash/lca/lca_utils.py
This is a convenience function to do `";".join(lca_utils.zip_lineage(lineage))`.
> [WIP] Add a 'display_lineage' function to lca_utils.py

- .readthedocs.yml
- doc/environment.yml
- doc/release.md
This PR uses the [conda support][0] to install Rust and fix the build errors in Read the Docs.
(Also add step 0 to release docs: check if docs are building before cutting a new release!)
[0]: https://docs.readthedocs.io/en/stable/guides/conda.html
> Fix read the docs build

- .github/workflows/rust.yml
- setup.py
- src/core/Cargo.toml
Set up GitHub Actions to publish the Rust crate to [crates.io][0] when there is a new tag. It also publishes the `wasm-pack` generated package (webassembly) to [NPM][1].
I also started using `r` as the prefix for Rust releases, like [`r0.3.0`][2]. This doesn't conflict with the sourmash regular versioning (which starts with `v`, as in [`v3.0.0`][3]).
And... using `r` triggered an error for calculating the Python version :rofl: 
So there is a [fix to `setuptools_scm`][4] to account only for `v` tags when calculating versions.
[0]: https://crates.io/crates/sourmash
[1]: https://www.npmjs.com/package/sourmash
[2]: https://github.com/dib-lab/sourmash/releases/tag/r0.3.0
[3]: https://github.com/dib-lab/sourmash/releases/tag/v3.0.0
[4]: https://github.com/pypa/setuptools_scm/pull/316
without a …
> [MRG] set up publishing workflow for NPM and crates.io

- doc/environment.yml
I noticed the RTD build failed, and it was because Python 3.8 was being used. Since `khmer` (and many other projects) don't have 3.8 wheels yet, it goes over the time limit that RTD imposes (15 minutes) because it has to build everything from source.
Using 3.7 brings [build time down to 403 seconds][0], which still leave enough time to avoid hitting the limit in the near future.
[0]: https://readthedocs.org/projects/sourmash/builds/10210318/
> use python 3.7 in RTD build

- include/sourmash.h
- sourmash/_minhash.py
- sourmash/lca/lca_utils.py
- src/core/src/ffi/minhash.rs
Calling `.add_hash()` on a MinHash sketch is fine, but if you're calling it all the time it's better to pass a list of hashes and call `.add_many()` instead. Before this PR `add_many` just called `add_hash` for each hash it was passed, but now it will pass the full list to Rust (and that's way faster).
No changes for public APIs, and I changed the `_signatures` method in LCA to accumulate hashes for each sig first, and then set them all at once. This is way faster, but might use more intermediate memory (I'll evaluate this now).
> Do add_many in Rust, use it in LCA _signatures

- .github/workflows/metadata.yml
- .github/workflows/rust.yml
The [Software Heritage] project has an API for triggering new snapshots of the code. I added a new job to GitHub Actions to trigger it on new tags.
[Software Heritage]: https://www.softwareheritage.org/
> Trigger new Software Heritage archival snapshot on new tags

- .gitattributes
How is this not bothering you?!?!
Just kidding, it was an easy change, and should make the repo's language stats summary a bit less bonkers.
> Ignore .sig and .sbt files for repo language stats

- sourmash/cli/categorize.py
- sourmash/cli/compare.py
- sourmash/cli/gather.py
- sourmash/cli/import_csv.py
- sourmash/cli/lca/classify.py
- sourmash/cli/lca/gather.py
- sourmash/cli/lca/summarize.py
- sourmash/cli/search.py
- sourmash/cli/sig/describe.py
- sourmash/cli/sig/downsample.py
- sourmash/cli/sig/export.py
- sourmash/cli/sig/extract.py
- sourmash/cli/sig/filter.py
- sourmash/cli/sig/flatten.py
- sourmash/cli/sig/ingest.py
- sourmash/cli/sig/intersect.py
- sourmash/cli/sig/merge.py
- sourmash/cli/sig/subtract.py
- sourmash/cli/watch.py
- sourmash/commands.py
- sourmash/lca/command_classify.py
- sourmash/lca/command_gather.py
- sourmash/lca/command_summarize.py
- sourmash/sig/__main__.py
- sourmash/sourmash_args.py
- tests/test_sourmash.py
`argparse.FileType('wt')` is annoying because it opens the specified file immediately upon argument parsing, which overwrites it. As shown in #571, this can destroy outputs unnecessarily.
This PR changes most of the `FileType` arguments in sourmash to string filenames, which are only opened at the time of write. I add a `FileOutput` context manager that behaves properly wrt default arguments encountered in the wild.
Fixes #571, overwriting files even on error.
May pave the way for `--inplace` behavior, ref #625.
Also cleans up an accidental duplication of  the `describe` implementation 😆
> [MRG] refactor argparse.FileType out of sourmash argument handling.

- sourmash/cli/plot.py
- sourmash/commands.py
- tests/test_sourmash.py
Fixes #486. Also, bonus! Fixes an output bug that wasn't tested (error message when label number didn't match matrix size).
> add --labeltext to plot

- Makefile
- benchmarks/benchmarks.py
- include/sourmash.h
- setup.py
- sourmash/_minhash.py
- sourmash/cli/compute.py
- sourmash/command_compute.py
- sourmash/exceptions.py
- sourmash/signature.py
- src/core/Cargo.toml
- src/core/benches/compute.rs
- src/core/src/cmd.rs
- src/core/src/errors.rs
- src/core/src/ffi/cmd/compute.rs
- src/core/src/ffi/cmd/mod.rs
- src/core/src/ffi/minhash.rs
- src/core/src/ffi/mod.rs
- src/core/src/ffi/signature.rs
- src/core/src/signature.rs
- src/core/src/sketch/minhash.rs
- src/core/src/sketch/ukhs.rs
- src/core/src/wasm.rs
- src/core/tests/minhash.rs
- src/core/tests/signature.rs
- tests/test_sourmash_compute.py
This PR expose functionality in a way that doesn't requiring moving all the Python compute code into Rust.
- I moved the internal functions from compute (`make_minhashes`, `add_seq`, `build_siglist`, `save_siglist`) to the outside scope, and made all the arguments explicit. It would be hard to refactor otherwise...
- `add_sequence` and `add_protein` methods for `SourmashSignature`. The idea here is to only cross the FFI layer once for each sequence, and being able to control better what can be improved on the Rust side (like using [rayon] for parallelization?).
- `add_protein` in `MinHash` was also moved to Rust, and it is 100x faster :rofl:  /cc @olgabot 
- Benchmarks in Python (for `add_protein`) and in Rust (for `add_sequence`)
- [`add_sequence` in Rust][9] is way simpler, and way …
> Compute oxidation

- .github/actions-rs/grcov.yml
- .github/workflows/rust.yml
- src/core/tests/signature.rs
Rust coverage reports are very finicky, trying out https://github.com/actions-rs/tarpaulin/ instead
> Use tarpaulin instead of grcov

- src/core/src/sketch/minhash.rs
> Improve sketching performance with lookup tables for complement and DNA validation

- include/sourmash.h
- sourmash/_minhash.py
- sourmash/commands.py
- sourmash/compare.py
- sourmash/sbt.py
- sourmash/sbtmh.py
- sourmash/signature.py
- src/core/src/ffi/minhash.rs
- src/core/src/index/mod.rs
- src/core/src/sketch/minhash.rs
- tests/test_sourmash.py
This is a merge into #856 
* add 'downsample' boolean parameter to rust `compare`, `similarity`, and `count_common`;
* refactor 'sourmash watch' to use new Index.search function instead of SBT-specific interface
* simplify and clean up sbt and sbtmh functionality around downsampling in searches; discovery of some unused functionality => removal.
Questions for @luizirber -
* advice requested on how I did the rust code for `compare` and `count_common`...
* I don't know how to call `add_many_with_abunds` in rust `similarity` function
* `containment_ignore_maxhash` is now identical in behavior to `contained_by(..., downsample=True)`. However, `contained_by` has a lot more checks and is presumably slower. In this PR I've replaced `containment_ignore_maxhash` with `contained_by`, but I'm happy …
> [WIP] oxidize downsampling in various similarity functions

- src/core/src/sketch/minhash.rs
- src/core/tests/minhash.rs
In #860 I described a performance issue in the sketching of DNA sequences: characters were repeatedly rechecked for their validity. The approach by @luizirber vastly speeds up the checking of characters (#861). However, most characters were still checked up to k times. Also, some valid k-mers were now missed due to a small logic error.
This pull request comes in three parts.
1. An initially failing unit test, showcasing the regression introduced in a07dd85.
2. Avoid rechecking valid characters.
3. Remove fast path as it was slowing us down.
Here are the benchmarks:
```
add_sequence/valid      time:   [4.9079 ms 4.9765 ms 5.0571 ms]                               
change: [-7.5285% -6.2820% -4.8922%] (p = 0.00 < 0.05)
Performance has improved.
Found 1 outliers among 10 measurements (10.00%) …
```
> Improve sketching performance for DNA

- include/sourmash.h
- sourmash/_minhash.py
- sourmash/commands.py
- sourmash/compare.py
- sourmash/sbt.py
- sourmash/sbtmh.py
- sourmash/signature.py
- src/core/Cargo.toml
- src/core/src/errors.rs
- src/core/src/ffi/minhash.rs
- src/core/src/index/mod.rs
- src/core/src/sketch/minhash.rs
- src/core/tests/minhash.rs
- tests/test__minhash.py
- tests/test_signature.py
- tests/test_sourmash.py
The downsampling code we use in MinHash comparisons is ugly, so refactoring it makes sense. This does a fairly broad cleanup based on adding a `downsample` bool option to the `similarity` functions. 
More specifically, this PR:
* adds 'downsample' boolean parameters to rust `compare`, `similarity`, and `count_common` functions;
* adds explicit tests for a few non-trivial angular distance calculations
* refactors 'sourmash watch' to use new Index.search function instead of SBT-specific interface
* simplifies and cleans up sbt and sbtmh functionality around downsampling in searches, and removes some unused functionality that is confusing.
> Refactor and oxidize downsampling code in sbtmh.py

- .travis.yml
- Makefile
- doc/release.md
Change remaining `pip` commands to `python -m pip` in release docs.
Properly set the travis condition for building jobs (push to master, new `vX.Y.Z` tag, pull requests against any branch, cron jobs).
> Fix travis for 3.2 release

- sourmash/cli/__init__.py
- sourmash/cli/sig/__init__.py
- sourmash/cli/signature/__init__.py
- tests/test_cmd_signature.py
> re-add 'signature' as alias for 'sig'

- sourmash/sbt.py
- tests/test_sourmash.py
Fixes #883 by naming signatures in SBT FSStorage based on their md5sum, preventing name collisions.
Note that this change is fully backwards and forwards compatible, because it merely changes the names that are put in the SBT JSON file.
> name signatures based on md5sum, not on name()

- sourmash/cli/compare.py
- sourmash/commands.py
- tests/test_sourmash.py
Error out with correct error messages when files don't exist or no signatures are found.
Also adds a `-f/--force` argument.
Fixes #858.
> Better sourmash compare error handling

- include/sourmash.h
- sourmash/_minhash.py
- src/core/src/ffi/minhash.rs
`kmerminhash_mins_push` and `kmerminhash_abunds_push` are too low level to expose on the C API, since they can leave the MinHash in an invalid state. This PR removes them and add `kmerminhash_set_abundances` instead, which doesn't assume as much.
It would be nice to have a `add_hash_with_abundance` and avoid the `add_many` behavior (calling `add_hash` in a loop), but that can be done later.
> Replace mins_push and abunds_push with set_abundances

- src/core/src/sketch/minhash.rs
- tests/test__minhash.py
Found this while updating #661. All our tests use scaled MH, so this didn't pop up...
> bug: add_hash with num doesn't set abundances properly

- .github/workflows/hypothesis.yml
- setup.py
- src/core/src/sketch/minhash.rs
- tests/conftest.py
- tests/test__minhash_hypothesis.py
Fixes #890
Also return early instead of nesting `if` statements.
> add_hash_with_abundance method in core library

- .gitignore
- doc/api-example.md
- doc/api.rst
- doc/conf.py
- include/sourmash.h
- setup.py
- sourmash/__init__.py
- sourmash/_minhash.py
- sourmash/index.py
- sourmash/sbt.py
- src/core/src/ffi/minhash.rs
- src/core/src/sketch/minhash.rs
- tests/test__minhash.py
Minor refactoring:
* Move Python `MinHash.similarity(...)` entirely into Rust, fix Rust function up a bit.
* Add Python `MinHash.angular_similarity(...)` method.
* Remove `MinHash.containment_ignore_maxhash` usage entirely from Python and Rust, while leaving as part of the Python MinHash API.
* Remove unused `deprecation` import in sbt.py.
* deprecate `MinHash.containment_ignore_maxhash` as of v3.3; remove from Rust.
* deprecate `MinHash.compare` as of v3.3; remove from Rust.
* deprecate `MinHash.intersection` as of v3.3.
* add or update MinHash class/method docstrings.
TODO:
* maybe: write Python `MinHash` object API tests/docs.
* maybe: fix unnamed exception in rust `angular_similarity` method.
Ref #885.
major …
> more refactoring of MinHash API

- sourmash/lca/command_classify.py
- tests/test_lca.py
Fixes #900. Introduced bug in #883, where we apparently never actually tested `lca classify -o ...` :)
Briefly, the new `sourmash_args.FileOutput` context manager tracks whether it's working with stdout, and will not close it if it is. So this allows bugs where, if stdout is given, the fp returned by `FileOutput` is still valid; but if a filename is specified, the fp is closed.
I verified by manual inspection that this isn't happening anywhere else in the code base.
> Fix `lca classify` bug with -o

- .github/workflows/asv.yml
- .github/workflows/rust.yml
- .github/workflows/rust_publish.yml
asv benchmarks are broken in GitHub Actions because a new `virtualenv` was released and removed the `--no-site-packages` flag (which is the default now). Keep older virtualenv until `asv` is fixed.
Rust tags were not being built for the last releases (`r0.4.0` and `r0.5.0`) and I ran the publish commands (to crates.io and npm) manually. They should trigger next time with the fix in this PR.
> (build) pin virtualenv version for asv, and also run GH actions on rust version tags

- setup.py
- tests/test__minhash.py
Added a test for triggering the bug, still need to figure out a fix :grimacing: 
> set_abundances fails with large signatures

- doc/developer.md
As mentioned [here](https://github.com/dib-lab/sourmash/issues/926) update developer docs for `ImportError: cannot import name 'to_bytes'`.
> Add make clean & rustup update to dev docs

- sourmash/cli/compare.py
- sourmash/cli/compute.py
- sourmash/cli/gather.py
- sourmash/cli/search.py
This makes `sourmash compute` return:
```
sourmash compute
usage: 
sourmash compute -k 21,31,51 *.fa *.fq
This will create MinHash sketches at k-mer sizes of 21, 31 and 51, for
all FASTA and FASTQ files in the current directory, and save them in
signature files ending in '.sig'. You can rapidly compare these files
with `compare` and query them with `search`, among other operations;
see the full documentation http://sourmash.rtfd.io/.
The key options for compute are:
* `-k/--ksize <int>[, <int>]: k-mer size(s) to use, e.g. -k 21,31,51
* `-n/--num <int>` or `--scaled <int>`: set size or resolution of sketches
* `--track-abundance`: track abundances of hashes (default False)
* `--dna or --protein`: nucleotide and/or protein signatures (default `--dna`)
* `--merge <name>`: compute a merged …
```
> [MRG] Trial improvements to sourmash argparse output for compute.

- sourmash/cli/compute.py
- sourmash/command_compute.py
- tests/test_sourmash_compute.py
Fixes #472 by adding `--outdir` to sourmash compute for use when neither `--merge` nor `--output` are specified.
Also simplifies and refactors some of the `sourmash` compute command code.
---
> [MRG] Add --outdir argument to `sourmash compute`

- .travis.yml
- setup.py
- tox.ini
~~`ipfshttpclient` is broken for large files, this is an ugly solution until https://github.com/ipfs/py-ipfs-http-client/pull/194 is merged and released.~~
Fixed in 0.4.13.
> [MRG] update ipfshttpclient version

- sourmash/lca/lca_db.py
- tests/test_lca.py
In [2020-cami](https://github.com/luizirber/2020-cami) I built an LCA index out of an SBT index ([relevant snakemake rules](https://github.com/luizirber/2020-cami/blob/master/Snakefile#L349L385)). While writing a script for extracting accessions from an index (in https://github.com/dib-lab/2019-12-12-sourmash_viz) I noticed that the `.signatures` method for LCA is not returning the original name from the signature, but the md5sum.
So, how does `gather` return the correct name? :thinking: 
Turns out that the logic for picking the right name is in `find_signatures`, so I just moved it to `_signatures` instead (and made `_signatures` store `Signature`s instead of `MinHash`s). Now signatures from the `.signatures` method have the original signature name.
without a major version increment. …
> make LCA signatures() method return signatures with the correct original name

- doc/conf.py
revamped the docs config per https://www.sphinx-doc.org/en/master/usage/markdown.html
> [MRG] fix markdown rendering on readthedocs / sphinx 3.x

- .github/workflows/khmer.yml
- .github/workflows/rust.yml
- .travis.yml
- include/sourmash.h
- setup.py
- sourmash/cli/info.py
- sourmash/commands.py
- sourmash/nodegraph.py
- sourmash/sbt.py
- sourmash/sbt_storage.py
- sourmash/sbtmh.py
- src/core/Cargo.toml
- src/core/benches/nodegraph.rs
- src/core/src/ffi/nodegraph.rs
- src/core/src/ffi/signature.rs
- src/core/src/index/sbt/mod.rs
- src/core/src/sketch/nodegraph.rs
- tests/test_nodegraph.py
- tests/test_sbt.py
- tox.ini
Main benefits:
- Read/write Nodegraph to/from buffers (no intermediate temporary files)
- Remove dep on khmer (but can still convert this Nodegraph into a khmer.Nodegraph)
> [MRG] replace khmer.Nodegraph with rust nodegraph

- doc/tutorials-lca.md
- sourmash/lca/command_index.py
- tests/test_lca.py
Update `sourmash lca index` error message  about lca index and too few species so that it's a proper error message and not an unhandled Exception. Fix test and tutorial to match.
Fixes #958 
> [MRG] Improve lca index error

- sourmash/lca/lca_db.py
- sourmash/sbt.py
- tests/test_lca.py
- tests/test_sbt.py
Now that the `LCA_Database` refactor in #946 has landed, we can simplify some of the test code in #942. This led to discovering a bug where `LCA_Database._find_signatures()` was using `Counter.items()` rather than `Counter.most_common()` to sort matches, which yielded results in the wrong order. Fixed! There's now an explicit test for this in LCA and SBT databases.
Separately, this highlights an inconsistency in `Index.gather()` - right now, `gather` returns only one match from LCA databases, but multiple from SBTs and LinearIndex. I don't think it makes sense to return multiple matches from gather... For sourmash 4, we might want to have gather return the best single result, rather than a list of results.
---
major …
> [MRG] fix bug when using Python 3.5 and before; refactor LCA_Database tests

- doc/kmers-and-minhash.ipynb
- doc/sourmash-collections.ipynb
- doc/sourmash-examples.ipynb
- doc/tutorials.md
- doc/using-LCA-database-API.ipynb
- sourmash/lca/lca_db.py
- tests/test_lca.py
Put together a Jupyter Notebook for the `LCA_Database` API; see #965 for motivation/request.
[View notebook on branch](https://github.com/dib-lab/sourmash/blob/doc_lca_db_api/doc/using-LCA-database-API.ipynb)
In the process, I figured out that `lineage_to_lids` was redundant with `lineage_to_lid` and removed the former, which led to me realizing that `lineage_to_lid` wasn't being properly built on database load, so I fixed that, too.
---
> [MRG] Document and (lightly) fix the LCA_Database API.

- setup.py
When setting up a v3.3.0 release, I ran into a problem with enum34 and python version incompatibilities -- briefly, when installing enum34 with pip install, I get
```
AttributeError: module 'enum' has no attribute 'IntFlag'  
``
This uses the [enum-compat package as a solution, via StackOverflow](https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag).
@luizirber approved this via slack :)
---
> [MRG] switch to enum-compat instead of enum34

- setup.py
specify python versions for which enum34 should be installed.
ref #979 
fixes #980
> fix enum34/python version mismatch more cleanly than #979

- sourmash/cli/index.py
Adds a `compute`-like usage output for `sourmash index`. In particular, mentions `.sbt.zip` behavior.
Partly addresses #973 
> [MRG] upgrade sourmash index usage docs on CLI

- tests/test_lca.py
There are two tests generating files outside the temporary directory...
> [MRG] Fix two temporary files output locations in tests

- tests/test_lca.py
- tests/test_lca_functions.py
So, I hadn't thought much about gather and needed to wrap my head around the gather_assignments functionality when lineages match, but one is more detailed: 
We keep the more detailed info, so  `a;b;d` + `a;b;d;e` yields `a;b;d;e`
This makes decent sense to me, as we always want to gather the best matches, and can summarize up later. But it's a little unintuitive to me that the count of `a;b;d` is 0 (abund test 4).
@ctb can you explain pls?
> functionality re: lineages that match but have addl taxonomic detail?

- sourmash/lca/command_gather.py
- sourmash/lca/lca_db.py
- sourmash/sbt.py
- tests/test_lca.py
In #1013, we added non-DNA LCA databases but failed to check that lca gather worked on them. This is now fixed. Also adds tests for loading LCA databases with incompatible moltypes, which should fail. And adds a deprecation warning for sourmash lca gather, which will be removed in future versions.
Fixes #1028 
Fixes #728 
----
> Fix lca gather to work on non-DNA databases.

- tests/sourmash_tst_utils.py
- tests/test_sourmash.py
- tests/test_sourmash_compute.py
This PR removes all references to the old run_shell_cmd function and replaces it making use of the @utils.in_tempdir decorator
Fixes #987 
> Refactor functions that use run_shell_cmd() function in test_sourmash.py and test_sourmash_compute.py per #987

- doc/api-example.md
Changes the temp directory name from a constant `/tmp/` to a unique name.
Fixes #1007 
> Doctest permission error

- Makefile
Adds .PHONY to the 'doc' target so as to force a docs build attempt.
This is a PR into #1021.
> Update #1021 with a Makefile fix.

- .travis.yml
> [CI] use install scripts from py-ipfs-http-client

- .github/workflows/rust.yml
- src/core/Cargo.toml
niffler 2.2.0 was released this morning, and now the `gz` compression is optional too (like `bz2` and `lzma` were before). Because we disable the default features it broke sourmash (because the `niffler` version was too lax).
This fixes the build errors in #1059 
> be more strict on niffler versions, add new gz feature to it

- sourmash/lca/lca_utils.py
- tests/test_lca_functions.py
Add some useful functions to sourmash.lca.lca_utils. Right now they're mostly used in charcoal.
Fixes #458 
> [MRG] add is_lineage_match, pop_to_rank, make_lineage to lca_utils

- doc/classifying-signatures.md
- tests/test_sourmash.py
Updates `doc/classifying-signatures.md` with abundance projection details.
Fixes https://github.com/dib-lab/sourmash/issues/1041
> [MRG] Improve documentation around abundance projection

- sourmash/lca/command_index.py
- sourmash/lca/lca_db.py
- tests/test_lca.py
LCA databases cannot be created with `num` signatures; while `lca index` does error out, it does so with an uninformative error about downsampling. This improves the lca index error message.
Fixes #1029 
Fixes #462
> [MRG] improve lca index error message when inserting num signature

- sourmash/commands.py
- sourmash/sbt.py
- sourmash/sig/__main__.py
- sourmash/sourmash_args.py
- tests/test_sourmash.py
Partial fix for #1082
```
% sourmash sig describe podar-ref.sbt.zip  podar-ref.sbt.zip podar-ref.lca.json.gz  ../charcoal/db/gtdb-release89-k31.sbt.zip  > /dev/null
```
produces
```
loaded 64 sigs from 'podar-ref.sbt.zip'
loaded 64 sigs from 'podar-ref.sbt.zip'
loaded 64 sigs from 'podar-ref.lca.json.gz'
...loading from '../charcoal/db/gtdb-release89-k31.sbt.zip' / 510 sigs total
```
This is all UX tweaking, no new tests.
> [MRG] add initial progress reporting wrapper for load_file_as_signatures

- doc/release.md
Updates to release procedure based on following release notes for v3.4.0 (#1100):
* replace ssh url with origin
* note travis build generates artifacts
* rust install / update instructions
> [MRG] Minor updates to release procedure

- sourmash/sig/__main__.py
This PR calls `minhash.is_compatible(...)` to check for MinHash compatibility before intersecting two MinHashes.
Fixes #1107 
> MinHash compatibility check to sourmash sig intersect

- sourmash/cli/lca/classify.py
- sourmash/lca/command_classify.py
- tests/test_lca.py
This PR adds command line option of `--majority` to `lca classify` which will use the **majority vote** algorithm instead of **lca**.
Fixes #984
> Adds --majority option to classify using majority vote algorithm

- doc/databases.md
It was good while it lasted: osf+gdrive has quota limits, so reverting back to S3 for now...
> (docs) revert SBT databases links back to S3

- README.md
Many updates --
* remove HTML boilerplate at top of README
* remove mention of Rust from user-focused installation (#983)
* add cffi, numpy, matplotlib, scipy as documented requirements; remove ijson mention
* remove bioconda setup instructions since `-c` is now specified explicitly
* adjust language to point out that conda installs latest released version; link to releases page.
* adjust one line description at top
* adjust "who develops sourmash" a bit
Fixes #983 
Addresses part of #1109 
> [MRG] simplify and clean up README

- sourmash_lib/__init__.py
- tests/test_deprecated.py
- tests/test_index.py
Fixes #441.
As in https://github.com/dib-lab/sourmash/pull/1128#issuecomment-667690185, I used `FutureWarning` instead of `DeprecationWarning` so it would show up without any special configuration.
> [MRG] deprecate `import sourmash_lib`

- doc/developer.md
- doc/release.md
- tests/test_deprecated.py
This updates the docs to remove mentions of these two no-longer-needed packages.
> [MRG] remove mentions of ijson and khmer
