dib-lab/sourmash

setup.py
Fix for #6 by explicitly including header locations in setup.py
=> try fixing includes for @sjackman

paper.bib
:wave: I made this edit when processing the final JOSS paper. Basically as things currently stand the bibtex is invalid...
=> Fixing bibtex entry (missing commas)

.travis.yml, pytest.ini, tox.ini
=> Use travis for builds again, fix Tox configs

sourmash_lib/test__minhash.py
=> ctb additions to #49

sourmash_lib/__main__.py, sourmash_lib/sourmash_args.py
=> extracted --protein/--dna into sourmash_args.py

sourmash_lib/sourmash_tst_utils.py, sourmash_lib/test_sourmash.py
=> Some basic tests for `sourmash watch` and `sourmash categorize`

sourmash_lib/__main__.py
=> Fix a problem with `categorize` where it re-categorizes sigs.

doc/more-info.rst
=> add list of blog posts

sourmash_lib/commands.py, sourmash_lib/test_sourmash.py
=> [MRG] Generate valid JSON when computing multiple signatures

sourmash_lib/commands.py, tests/test_sourmash.py
Fixes the output to a file found by @taylorreiter
=> Fix format specifier when outputting to a file

sourmash_lib/commands.py, tests/test_sourmash.py
Fixes #205 
Changed search output so that it only shows the limit
when there are more results than the limit.
=> [MRG] Modify search output

sourmash_lib/commands.py, tests/test_sourmash.py
=> [MRG] add explicit test for stdout being json compliant

doc/Makefile, doc/_templates/navigation.html, doc/databases.md
Fixes #233. Fixes database formatting in `databases.md`.
=> Fix various documentation formatting issues

sourmash_lib/commands.py, sourmash_lib/signature.py, tests/test_sourmash.py
=> [MRG] add downsampling to containment function

sourmash_lib/commands.py
A small fix to printing stuff out during `compute`.
=> [MRG] fix output with notify

tests/test_sourmash.py
=> [MRG] bugfix: Check for both possible occurrences in `test_gather_metagenome_downsample`

README.md
=> [MRG] Remove gitter channel

sourmash_lib/kmer_min_hash.hh
Fixes #330 (stolen from https://github.com/dib-lab/khmer/pull/1791 )
=> [MRG] Update revcomp from khmer

doc/more-info.rst
* Adds citations and blogposts to `doc/more-info.rst` - fixes #336.
* Adds link to @brooksph [ASM poster](https://osf.io/mu4gk/) - fixes #272.
=> [MRG] Update documentation in various ways.

tests/test_sourmash.py
Note, this is into #359 not master.
=> [MRG] add a more explicit test for sourmash compute

sourmash_lib/signature_json.py, tests/test_signature.py
=> [MRG] Minify JSON

doc/tutorials-lca.md
=> [MRG] update download location of lca db

doc/index.rst
Whoops. Fixes #393 where I introduced some Markdown formatting in index.rst. Will emergency merge.
=> [MRG] fix reST in updated docs

README.md, doc/index.rst
=> [MRG] update README to include more install options

README.md, doc/developer.md, sourmash/__main__.py
=> [MRG] Fix / update some developers docs.

sourmash/commands.py, tests/test_sourmash.py
=> [MRG] fix error caused by no matches returned from gather

README.md
When I first saw sourmash I thought I couldn't use it because I had RNA not DNA. And now I see you do protein signatures too! So I propose this change so others don't get deterred either.
=> DNA --> nucleotide and protein

doc/tutorials.md
Fix #498
(thanks @ljcohen!)
Ready for review and merge @taylorreiter @brooksph
=> [docs] Fix download link for ecoli reads

doc/index.rst
Per https://twitter.com/indianalytics/status/1009081995354345473  thx @Schallaven 
=> [MRG] fix tutorial links on index

sourmash/commands.py
Forgot to push this before merging! Arghh! #533
=> Minor fix to #533

doc/tutorials-lca.md
update tutorial link for lca db
=> update lca link

README.md, tests/test_sourmash.py
=> [MRG] Fix path issue with numpy and 2.7 (and travis badge)

doc/index.rst
=> remove the pre-release note

README.md
=> Added conda-forge, bioconda; Updated Python version to 3.7

README.md
Add 'conda-forge' and 'bioconda' channels to `conda install` command in README.
Should fix #686.
=> [MRG] update conda install instructions in README to specify bioconda

utils/hashvals-to-signature.py
=> Fix typo in hash-to-signature-to-kmer utility scripts 

setup.py, sourmash/command_compute.py, sourmash/commands.py, sourmash/compare.py, sourmash/lca/command_classify.py, sourmash/lca/command_compare_csv.py, sourmash/lca/command_gather.py, sourmash/lca/command_index.py, sourmash/lca/command_rankinfo.py, sourmash/lca/command_summarize.py, sourmash/lca/lca_utils.py, sourmash/sig/__main__.py, sourmash/signature.py, sourmash/sourmash_args.py, utils/check-tree.py, utils/compute-dna-mh-another-way.py, utils/compute-input-prot-another-way.py, utils/compute-prot-mh-another-way.py
Sets up [LGTM](https://lgtm.com/projects/g/dib-lab/sourmash/) and clean up some of the alerts. I liked the service because
- It's positive reinforcement on the checks (only account for new issues introduced, not about forcing the submitter to fix previous errors)
- Alerts are informative (the explanations are very good, and I learned new things)
- It did catch things we didn't pick up in tests (like `similarity` being [called with the wrong number of arguments](https://lgtm.com/projects/g/dib-lab/sourmash/snapshot/94902a93a72de90b8b8a1b45698fbfc213be36ea/files/sourmash/compare.py#x741d02e80a2e1aac:1)
This also restrict `ijson` versions, because they have a breaking change in 2.5 (see #737)
major version number …
=> LGTM setup and initial fixes

doc/release.md
(they are quite outdated)
I also added pointers to update the Bioconda recipe.
=> Update release docs

doc/index.rst
=> [MRG] Add the F1000 paper reference to the front page of the docs.

.travis.yml, tests/test_cmd_signature.py
=> Force signature order in test_sig_filter_1 to fix heisenbug

doc/release.md
Fix some formatting issues, and add new announcement tweet.
=> Release process update for 3.1.0

sourmash/search.py, tests/test_sourmash.py
=> [MRG] Fix 'gather' threshold reporting to report threshold, not match.

.github/workflows/rust.yml, .travis.yml, src/core/tests/minhash.rs, tox.ini
Python dev mode activates some checks that are too expensive for regular runtime, but are useful when running tests. More info: https://docs.python.org/dev/library/devmode.html
I also changed travis build configs to allow building PRs against any branch, not only master.
Merging this into #863 to see if travis will build.
=> Use Python dev mode on 3.7, and build PRs that merge against any branch

doc/developer.md
=> [MRG] update docs for how to run Rust tests

doc/release.md
=> [MRG] update release docs

doc/command-line.md, sourmash/sourmash_args.py, tests/test_sourmash.py
A first attempt at #1092.
Also adds a table of contents to the command-line docs, which is pretty nice!
=> [MRG] Update cli docs
